import { getTimestamp } from "./analytics.js";
import {
  formatNumber,
  formatFloat,
  sanitizeText,
  toISODate,
  formatDisplayDate,
  formatTimestampDisplay,
} from "./utils.js";
import {
  SECTION_NAV_ITEMS,
  SEARCH_RESULT_LIMIT,
  ONBOARDING_STEPS,
} from "./appConstants.js";
import {
  setStatusCallback,
  updateStatus,
  getDatasetEntries,
  setDatasetEntries,
  setDatasetAnalytics,
  getDatasetAnalytics,
  setDatasetLabel,
  getDatasetLabel,
  setCurrentRange,
  getCurrentRange,
  setCustomRange,
  getCustomRange,
  saveChatDataset,
  listChatDatasets,
  getChatDatasetById,
  setActiveChatId,
  getActiveChatId,
  addSavedView,
  getSavedViews,
  updateSavedView,
  removeSavedView,
  clearSavedViews,
  setCompareSelection,
  getCompareSelection,
  getSearchState,
  getHourlyState,
  updateHourlyState,
  resetHourlyFilters,
  getWeekdayState,
  updateWeekdayState,
  getCachedAnalytics,
  setCachedAnalytics,
  clearAnalyticsCache,
  setDatasetFingerprint,
  getDatasetFingerprint,
  setDatasetParticipantDirectory,
  resetWeekdayFilters,
  computeDatasetFingerprint,
} from "./state.js";
import {
  formatHourLabel,
  computeTimeOfDayDataset,
} from "./analytics/activity.js";
import {
  API_BASE,
  BRAND_NAME,
  RELAY_SERVICE_NAME,
  STATUS_AUTO_HIDE_DELAY_MS,
  STATUS_EXIT_DURATION_MS,
  motionPreferenceQuery,
  initialReduceMotionPreferred,
} from "./config.js";
import { createDatasetEmptyStateManager } from "./ui.js";
import {
  createAppDomRefs,
  fetchJson,
  COMPACT_STORAGE_KEY,
  REDUCE_MOTION_STORAGE_KEY,
  HIGH_CONTRAST_STORAGE_KEY,
} from "./appShell/index.js";
import { bootstrapAppShellRuntime } from "./appShell/runtimeBootstrap.js";
import { createAppControllerWiring } from "./appShell/controllerWiring.js";
import { createAppCompositionAssembly } from "./appShell/compositionAssembly.js";

const {
  statusEl,
  relayBannerEl,
  relayBannerMessage,
  relayBannerMeta,
  relayOnboardingSteps,
  summaryEl,
  participantsBody,
  participantsNote,
  participantsTopSelect,
  participantsSortSelect,
  participantsTimeframeSelect,
  participantPresetButtons,
  rangeSelect,
  chatSelector,
  relayStatusEl,
  relayAccountEl,
  relayStartButton,
  relayStopButton,
  relayLogoutButton,
  relayReloadAllButton,
  relayClearStorageButton,
  relayQrContainer,
  relayQrImage,
  relayHelpText,
  relaySyncProgressEl,
  relaySyncChatsMeta,
  relaySyncMessagesMeta,
  reduceMotionToggle,
  highContrastToggle,
  customControls,
  customStartInput,
  customEndInput,
  customApplyButton,
  hourlyTopHourEl,
  brushSummaryEl,
  filterNoteEl,
  hourlyChartEl,
  hourlyAnomaliesEl,
  dailyChartEl,
  dailyAvgDayEl,
  weeklyChartEl,
  weeklyCumulativeEl,
  weeklyRollingEl,
  weeklyAverageEl,
  weekdayChartEl,
  weekdayFilterNote,
  weekdayToggleWeekdays,
  weekdayToggleWeekends,
  weekdayToggleWorking,
  weekdayToggleOffhours,
  weekdayHourStartInput,
  weekdayHourEndInput,
  messageTypeSummaryEl,
  messageTypeNoteEl,
  downloadPdfButton,
  downloadTimeOfDayButton,
  downloadParticipantsButton,
  downloadHourlyButton,
  downloadDailyButton,
  downloadWeeklyButton,
  downloadWeekdayButton,
  downloadMessageTypesButton,
  downloadSentimentButton,
  downloadChatJsonButton,
  sentimentSummaryEl,
  sentimentTrendNote,
  sentimentDailyChart,
  sentimentPositiveList,
  sentimentNegativeList,
  savedViewNameInput,
  saveViewButton,
  savedViewList,
  applySavedViewButton,
  deleteSavedViewButton,
  savedViewGallery,
  compareViewASelect,
  compareViewBSelect,
  compareViewsButton,
  compareSummaryEl,
  searchForm,
  searchKeywordInput,
  searchParticipantSelect,
  searchStartInput,
  searchEndInput,
  resetSearchButton,
  downloadSearchButton,
  searchResultsSummary,
  searchResultsList,
  searchInsightsEl,
  searchProgressEl,
  searchProgressTrack,
  searchProgressBar,
  searchProgressLabel,
  highlightList,
  downloadMarkdownButton,
  downloadSlidesButton,
  logDrawerToggleButton,
  logDrawerEl,
  logDrawerCloseButton,
  logDrawerClearButton,
  logDrawerList,
  logDrawerConnectionLabel,
  globalProgressEl,
  globalProgressLabel,
  toastContainer,
  compactToggleButton,
  onboardingOverlay,
  onboardingCopyEl,
  onboardingStepLabel,
  onboardingSkipButton,
  onboardingNextButton,
  heroStatusBadge,
  heroStatusCopy,
  datasetEmptyCallout,
  datasetEmptyHeading,
  datasetEmptyCopy,
  sectionNavInner,
  timeOfDayWeekdayToggle,
  timeOfDayWeekendToggle,
  timeOfDayHourStartInput,
  timeOfDayHourEndInput,
  timeOfDayHourStartLabel,
  timeOfDayHourEndLabel,
  timeOfDaySparklineEl,
  timeOfDayBandsEl,
  timeOfDayCalloutsEl,
  timeOfDayChartContainer,
  pollsNote,
  pollsTotalEl,
  pollsCreatorsEl,
  pollsListEl,
  dashboardRoot,
  themeToggleInputs,
} = createAppDomRefs();

const datasetEmptyStateManager = createDatasetEmptyStateManager({
  calloutEl: datasetEmptyCallout,
  headingEl: datasetEmptyHeading,
  copyEl: datasetEmptyCopy,
  buttons: [
    downloadPdfButton,
    downloadMarkdownButton,
    downloadSlidesButton,
    downloadChatJsonButton,
    downloadParticipantsButton,
    downloadHourlyButton,
    downloadDailyButton,
    downloadWeeklyButton,
    downloadWeekdayButton,
    downloadTimeOfDayButton,
    downloadMessageTypesButton,
    downloadSentimentButton,
    downloadSearchButton,
  ],
});
const setDatasetEmptyMessage = datasetEmptyStateManager.setMessage;
const {
  encodeChatSelectorValue,
  setRemoteChatList,
  getRemoteChatList,
  getRemoteChatsLastFetchedAt,
  refreshChatSelector,
  handleChatSelectionChangeCore,
  analyticsRequestTracker,
  computeAnalyticsWithWorker,
  normalizeRangeValue,
  filterEntriesByRange,
  describeRange,
  updateCustomRangeBounds,
  handleRangeChange,
  applyCustomRange,
  searchController,
  savedViewsController,
  setDashboardLoadingState,
  setDataAvailabilityState,
  updateHeroRelayStatus,
  getDataAvailable,
  handleParticipantsTopChange,
  handleParticipantsSortChange,
  handleParticipantsTimeframeChange,
  handleParticipantPresetClick,
  handleParticipantRowToggle,
  getExportFilterSummary,
  getParticipantView,
  renderDashboard,
  ensureWeekdayDayFilters,
  ensureWeekdayHourFilters,
  rerenderHourlyFromState,
  rerenderWeekdayFromState,
  ensureDayFilters,
  syncHourlyControlsWithState,
  initThemeControls,
  getExportThemeConfig,
} = createAppControllerWiring({
  dom: {
    chatSelector,
    rangeSelect,
    customControls,
    customStartInput,
    customEndInput,
    customApplyButton,
    searchStartInput,
    searchEndInput,
    searchForm,
    searchKeywordInput,
    searchParticipantSelect,
    resetSearchButton,
    searchResultsSummary,
    searchResultsList,
    searchInsightsEl,
    searchProgressEl,
    searchProgressTrack,
    searchProgressBar,
    searchProgressLabel,
    savedViewNameInput,
    saveViewButton,
    savedViewList,
    applySavedViewButton,
    deleteSavedViewButton,
    savedViewGallery,
    compareViewASelect,
    compareViewBSelect,
    compareViewsButton,
    compareSummaryEl,
    dashboardRoot,
    heroStatusBadge,
    heroStatusCopy,
    participantsTopSelect,
    participantsSortSelect,
    participantsTimeframeSelect,
    participantsBody,
    summaryEl,
    participantsNote,
    participantPresetButtons,
    hourlyChartEl,
    filterNoteEl,
    brushSummaryEl,
    hourlyAnomaliesEl,
    hourlyTopHourEl,
    dailyChartEl,
    dailyAvgDayEl,
    weeklyChartEl,
    weeklyCumulativeEl,
    weeklyRollingEl,
    weeklyAverageEl,
    weekdayChartEl,
    weekdayFilterNote,
    weekdayToggleWeekdays,
    weekdayToggleWeekends,
    weekdayToggleWorking,
    weekdayToggleOffhours,
    weekdayHourStartInput,
    weekdayHourEndInput,
    timeOfDayWeekdayToggle,
    timeOfDayWeekendToggle,
    timeOfDayHourStartInput,
    timeOfDayHourEndInput,
    timeOfDayHourStartLabel,
    timeOfDayHourEndLabel,
    timeOfDayChartContainer,
    timeOfDaySparklineEl,
    timeOfDayBandsEl,
    timeOfDayCalloutsEl,
    sentimentSummaryEl,
    sentimentTrendNote,
    sentimentDailyChart,
    sentimentPositiveList,
    sentimentNegativeList,
    messageTypeSummaryEl,
    messageTypeNoteEl,
    pollsListEl,
    pollsTotalEl,
    pollsCreatorsEl,
    pollsNote,
    highlightList,
    themeToggleInputs,
  },
  state: {
    listChatDatasets,
    getActiveChatId,
    setActiveChatId,
    getDatasetEntries,
    getDatasetLabel,
    setCurrentRange,
    setCustomRange,
    getCustomRange,
    getCachedAnalytics,
    setCachedAnalytics,
    setDatasetAnalytics,
    updateStatus,
    getDatasetAnalytics,
    getCurrentRange,
    addSavedView,
    getSavedViews,
    updateSavedView,
    removeSavedView,
    clearSavedViews,
    getCompareSelection,
    setCompareSelection,
    getHourlyState,
    updateHourlyState,
    getWeekdayState,
    updateWeekdayState,
  },
  utils: {
    formatNumber,
    formatFloat,
    sanitizeText,
    formatDisplayDate,
    getTimestamp,
    toISODate,
  },
  constants: {
    brandName: BRAND_NAME,
    searchResultLimit: SEARCH_RESULT_LIMIT,
  },
  callbacks: {
    syncHeroPillsWithRange: () => {},
  },
  dataStatus: {
    datasetEmptyStateManager,
    setDatasetEmptyMessage,
  },
});
const {
  exportParticipants,
  exportHourly,
  exportDaily,
  exportWeekly,
  exportWeekday,
  exportTimeOfDay,
  exportMessageTypes,
  exportChatJson,
  exportSentiment,
  exportSearchResults,
  handleDownloadMarkdownReport,
  handleDownloadSlidesReport,
  exportMessageSubtype,
  handleDownloadPdfReport,
  startRelaySession,
  stopRelaySession,
  syncRelayChats,
  isLogDrawerOpen,
  openLogDrawer,
  closeLogDrawer,
  initRelayControls,
  handleChatSelectionChange,
} = createAppCompositionAssembly({
  dom: {
    rangeSelect,
    globalProgressEl,
    globalProgressLabel,
    relayStartButton,
    relayStopButton,
    relayLogoutButton,
    relayReloadAllButton,
    relayStatusEl,
    relayAccountEl,
    relayQrContainer,
    relayQrImage,
    relayHelpText,
    relayBannerEl,
    relayBannerMessage,
    relayBannerMeta,
    relayOnboardingSteps,
    logDrawerToggleButton,
    logDrawerEl,
    logDrawerList,
    logDrawerConnectionLabel,
    relayClearStorageButton,
    relaySyncProgressEl,
    relaySyncChatsMeta,
    relaySyncMessagesMeta,
    logDrawerCloseButton,
    logDrawerClearButton,
  },
  state: {
    getDatasetFingerprint,
    getDatasetAnalytics,
    getDatasetEntries,
    getDatasetLabel,
    getCurrentRange,
    getSearchState,
    updateStatus,
    setDatasetEntries,
    setDatasetFingerprint,
    setDatasetParticipantDirectory,
    clearAnalyticsCache,
    setDatasetLabel,
    setCurrentRange,
    setCustomRange,
    resetHourlyFilters,
    resetWeekdayFilters,
    computeDatasetFingerprint,
    saveChatDataset,
    setCachedAnalytics,
    setDatasetAnalytics,
    setActiveChatId,
    getChatDatasetById,
    setDatasetEmptyMessage,
    fetchJson,
  },
  utils: {
    formatNumber,
    formatFloat,
    formatTimestampDisplay,
  },
  analytics: {
    computeTimeOfDayDataset,
    formatHourLabel,
  },
  constants: {
    brandName: BRAND_NAME,
    apiBase: API_BASE,
  },
  wiring: {
    getExportFilterSummary,
    getExportThemeConfig,
    getParticipantView,
    describeRange,
    filterEntriesByRange,
    normalizeRangeValue,
    analyticsRequestTracker,
    computeAnalyticsWithWorker,
    renderDashboard,
    updateCustomRangeBounds,
    encodeChatSelectorValue,
    setRemoteChatList,
    getRemoteChatList,
    getRemoteChatsLastFetchedAt,
    refreshChatSelector,
    savedViewsController,
    searchController,
    setDashboardLoadingState,
    setDataAvailabilityState,
    updateHeroRelayStatus,
    handleChatSelectionChangeCore,
  },
  electronAPI: window.electronAPI,
});

const runtimeEventBindings = {
  elements: {
    chatSelector,
    rangeSelect,
    customApplyButton,
    customStartInput,
    customEndInput,
    downloadParticipantsButton,
    downloadHourlyButton,
    downloadDailyButton,
    downloadWeeklyButton,
    downloadWeekdayButton,
    downloadTimeOfDayButton,
    downloadMessageTypesButton,
    downloadChatJsonButton,
    downloadSentimentButton,
    downloadMarkdownButton,
    downloadSlidesButton,
    downloadSearchButton,
    downloadPdfButton,
    participantsTopSelect,
    participantsSortSelect,
    participantsTimeframeSelect,
    participantPresetButtons,
    participantsBody,
    weekdayToggleWeekdays,
    weekdayToggleWeekends,
    weekdayToggleWorking,
    weekdayToggleOffhours,
    timeOfDayWeekdayToggle,
    timeOfDayWeekendToggle,
    timeOfDayHourStartInput,
    timeOfDayHourEndInput,
    weekdayHourStartInput,
    weekdayHourEndInput,
  },
  handlers: {
    handleChatSelectionChange,
    handleRangeChange,
    exportParticipants,
    exportHourly,
    exportDaily,
    exportWeekly,
    exportWeekday,
    exportTimeOfDay,
    exportMessageTypes,
    exportChatJson,
    exportSentiment,
    exportMessageSubtype,
    handleDownloadMarkdownReport,
    handleDownloadSlidesReport,
    exportSearchResults,
    handleDownloadPdfReport,
    handleParticipantsTopChange,
    handleParticipantsSortChange,
    handleParticipantsTimeframeChange,
    handleParticipantPresetClick,
    handleParticipantRowToggle,
  },
  deps: {
    updateStatus,
    applyCustomRange,
    updateWeekdayState,
    ensureWeekdayDayFilters,
    rerenderWeekdayFromState,
    ensureWeekdayHourFilters,
    updateHourlyState,
    getHourlyState,
    ensureDayFilters,
    syncHourlyControlsWithState,
    rerenderHourlyFromState,
  },
};

const runtimeBootstrapDeps = {
  initRelayControls,
  initThemeControls,
  setDataAvailabilityState,
  startRelaySession,
  stopRelaySession,
  searchController,
  savedViewsController,
  getDataAvailable,
  refreshChatSelector,
  updateStatus,
  relayServiceName: RELAY_SERVICE_NAME,
};

bootstrapAppShellRuntime({
  statusConfig: {
    setStatusCallback,
    statusEl,
    toastContainer,
    autoHideDelayMs: STATUS_AUTO_HIDE_DELAY_MS,
    exitDurationMs: STATUS_EXIT_DURATION_MS,
  },
  sectionNavConfig: {
    containerEl: sectionNavInner,
    navItemsConfig: SECTION_NAV_ITEMS,
  },
  compactConfig: {
    toggle: compactToggleButton,
    storageKey: COMPACT_STORAGE_KEY,
  },
  accessibilityConfig: {
    reduceMotionToggle,
    highContrastToggle,
    motionPreferenceQuery,
    initialReduceMotionPreferred,
    reduceMotionStorageKey: REDUCE_MOTION_STORAGE_KEY,
    highContrastStorageKey: HIGH_CONTRAST_STORAGE_KEY,
  },
  onboardingConfig: {
    overlayEl: onboardingOverlay,
    copyEl: onboardingCopyEl,
    stepLabelEl: onboardingStepLabel,
    skipButtonEl: onboardingSkipButton,
    nextButtonEl: onboardingNextButton,
    steps: ONBOARDING_STEPS,
  },
  keyboardDeps: {
    syncRelayChats,
    isLogDrawerOpen,
    closeLogDrawer,
    openLogDrawer,
  },
  eventBindings: runtimeEventBindings,
  bootstrapDeps: runtimeBootstrapDeps,
});
