import {
  SECTION_NAV_ITEMS,
  SEARCH_RESULT_LIMIT,
  ONBOARDING_STEPS,
} from "./appConstants.js";
import * as appState from "./state.js";
import {
  API_BASE,
  BRAND_NAME,
  RELAY_SERVICE_NAME,
  STATUS_AUTO_HIDE_DELAY_MS,
  STATUS_EXIT_DURATION_MS,
  motionPreferenceQuery,
  initialReduceMotionPreferred,
} from "./config.js";
import { createDatasetEmptyStateManager } from "./ui.js";
import {
  createAppDomRefs,
  fetchJson,
  COMPACT_STORAGE_KEY,
  REDUCE_MOTION_STORAGE_KEY,
  HIGH_CONTRAST_STORAGE_KEY,
} from "./appShell/index.js";
import { bootstrapAppShellRuntime } from "./appShell/runtimeBootstrap.js";
import { createAppControllerWiring } from "./appShell/controllerWiring.js";
import { createAppCompositionAssembly } from "./appShell/compositionAssembly.js";
import { createAppDomRefGroups } from "./appShell/domRefGroups.js";
import { createRuntimeBootstrapConfig } from "./appShell/runtimeBootstrapConfig.js";
import { buildControllerWiringArgs, buildCompositionAssemblyArgs } from "./appShell/entryConfig.js";
import {
  createControllerWiringConfig,
  createCompositionAssemblyConfig,
} from "./appShell/compositionConfig.js";

const appDomRefs = createAppDomRefs();
const {
  runtimeRefs,
  relayRefs,
  filterRefs,
  dashboardRefs,
  exportRefs,
  savedViewRefs,
  searchRefs,
} = createAppDomRefGroups(appDomRefs);

const {
  statusEl,
  toastContainer,
  compactToggleButton,
  reduceMotionToggle,
  highContrastToggle,
  onboardingOverlay,
  onboardingCopyEl,
  onboardingStepLabel,
  onboardingSkipButton,
  onboardingNextButton,
  sectionNavInner,
} = runtimeRefs;

const datasetEmptyStateManager = createDatasetEmptyStateManager({
  calloutEl: runtimeRefs.datasetEmptyCallout,
  headingEl: runtimeRefs.datasetEmptyHeading,
  copyEl: runtimeRefs.datasetEmptyCopy,
  buttons: [
    exportRefs.downloadPdfButton,
    exportRefs.downloadMarkdownButton,
    exportRefs.downloadSlidesButton,
    exportRefs.downloadChatJsonButton,
    exportRefs.downloadParticipantsButton,
    exportRefs.downloadHourlyButton,
    exportRefs.downloadDailyButton,
    exportRefs.downloadWeeklyButton,
    exportRefs.downloadWeekdayButton,
    exportRefs.downloadTimeOfDayButton,
    exportRefs.downloadMessageTypesButton,
    exportRefs.downloadSentimentButton,
    exportRefs.downloadSearchButton,
  ],
});
const setDatasetEmptyMessage = datasetEmptyStateManager.setMessage;
const {
  encodeChatSelectorValue,
  setRemoteChatList,
  getRemoteChatList,
  getRemoteChatsLastFetchedAt,
  refreshChatSelector,
  handleChatSelectionChangeCore,
  analyticsRequestTracker,
  computeAnalyticsWithWorker,
  normalizeRangeValue,
  filterEntriesByRange,
  describeRange,
  updateCustomRangeBounds,
  handleRangeChange,
  applyCustomRange,
  searchController,
  savedViewsController,
  setDashboardLoadingState,
  setDataAvailabilityState,
  updateHeroRelayStatus,
  getDataAvailable,
  handleParticipantsTopChange,
  handleParticipantsSortChange,
  handleParticipantsTimeframeChange,
  handleParticipantPresetClick,
  handleParticipantRowToggle,
  getExportFilterSummary,
  getParticipantView,
  renderDashboard,
  ensureWeekdayDayFilters,
  ensureWeekdayHourFilters,
  rerenderHourlyFromState,
  rerenderWeekdayFromState,
  ensureDayFilters,
  syncHourlyControlsWithState,
  initThemeControls,
  getExportThemeConfig,
} = createAppControllerWiring(
  buildControllerWiringArgs({
    ...createControllerWiringConfig({
      filterRefs,
      dashboardRefs,
      savedViewRefs,
      searchRefs,
      runtimeRefs,
      stateStore: appState,
      brandName: BRAND_NAME,
      searchResultLimit: SEARCH_RESULT_LIMIT,
      datasetEmptyStateManager,
      setDatasetEmptyMessage,
    }),
  }),
);
const compositionAssemblyWiring = {
  getExportFilterSummary,
  getExportThemeConfig,
  getParticipantView,
  describeRange,
  filterEntriesByRange,
  normalizeRangeValue,
  analyticsRequestTracker,
  computeAnalyticsWithWorker,
  renderDashboard,
  updateCustomRangeBounds,
  encodeChatSelectorValue,
  setRemoteChatList,
  getRemoteChatList,
  getRemoteChatsLastFetchedAt,
  refreshChatSelector,
  savedViewsController,
  searchController,
  setDashboardLoadingState,
  setDataAvailabilityState,
  updateHeroRelayStatus,
  handleChatSelectionChangeCore,
};
const {
  exportParticipants,
  exportHourly,
  exportDaily,
  exportWeekly,
  exportWeekday,
  exportTimeOfDay,
  exportMessageTypes,
  exportChatJson,
  exportSentiment,
  exportSearchResults,
  handleDownloadMarkdownReport,
  handleDownloadSlidesReport,
  exportMessageSubtype,
  handleDownloadPdfReport,
  startRelaySession,
  stopRelaySession,
  syncRelayChats,
  isLogDrawerOpen,
  openLogDrawer,
  closeLogDrawer,
  initRelayControls,
  handleChatSelectionChange,
} = createAppCompositionAssembly(
  buildCompositionAssemblyArgs({
    ...createCompositionAssemblyConfig({
      filterRefs,
      runtimeRefs,
      relayRefs,
      stateStore: appState,
      setDatasetEmptyMessage,
      fetchJson,
      brandName: BRAND_NAME,
      apiBase: API_BASE,
      wiring: compositionAssemblyWiring,
      electronAPI: window.electronAPI,
    }),
  }),
);

bootstrapAppShellRuntime(
  createRuntimeBootstrapConfig({
    filterRefs,
    exportRefs,
    dashboardRefs,
    relayRefs,
    runtimeRefs,
    handlers: {
      handleChatSelectionChange,
      handleRangeChange,
      exportParticipants,
      exportHourly,
      exportDaily,
      exportWeekly,
      exportWeekday,
      exportTimeOfDay,
      exportMessageTypes,
      exportChatJson,
      exportSentiment,
      exportMessageSubtype,
      handleDownloadMarkdownReport,
      handleDownloadSlidesReport,
      exportSearchResults,
      handleDownloadPdfReport,
      handleParticipantsTopChange,
      handleParticipantsSortChange,
      handleParticipantsTimeframeChange,
      handleParticipantPresetClick,
      handleParticipantRowToggle,
      initRelayControls,
      initThemeControls,
      setDataAvailabilityState,
      startRelaySession,
      stopRelaySession,
      searchController,
      savedViewsController,
      getDataAvailable,
      refreshChatSelector,
      updateStatus: appState.updateStatus,
    },
    deps: {
      updateStatus: appState.updateStatus,
      applyCustomRange,
      updateWeekdayState: appState.updateWeekdayState,
      ensureWeekdayDayFilters,
      rerenderWeekdayFromState,
      ensureWeekdayHourFilters,
      updateHourlyState: appState.updateHourlyState,
      getHourlyState: appState.getHourlyState,
      ensureDayFilters,
      syncHourlyControlsWithState,
      rerenderHourlyFromState,
    },
    relayServiceName: RELAY_SERVICE_NAME,
    statusConfig: {
      setStatusCallback: appState.setStatusCallback,
      statusEl,
      toastContainer,
      autoHideDelayMs: STATUS_AUTO_HIDE_DELAY_MS,
      exitDurationMs: STATUS_EXIT_DURATION_MS,
    },
    sectionNavConfig: {
      containerEl: sectionNavInner,
      navItemsConfig: SECTION_NAV_ITEMS,
    },
    compactConfig: {
      toggle: compactToggleButton,
      storageKey: COMPACT_STORAGE_KEY,
    },
    accessibilityConfig: {
      reduceMotionToggle,
      highContrastToggle,
      motionPreferenceQuery,
      initialReduceMotionPreferred,
      reduceMotionStorageKey: REDUCE_MOTION_STORAGE_KEY,
      highContrastStorageKey: HIGH_CONTRAST_STORAGE_KEY,
    },
    onboardingConfig: {
      overlayEl: onboardingOverlay,
      copyEl: onboardingCopyEl,
      stepLabelEl: onboardingStepLabel,
      skipButtonEl: onboardingSkipButton,
      nextButtonEl: onboardingNextButton,
      steps: ONBOARDING_STEPS,
    },
    keyboardDeps: {
      syncRelayChats,
      isLogDrawerOpen,
      closeLogDrawer,
      openLogDrawer,
    },
  }),
);
