import { getTimestamp } from "./analytics.js";
import {
  formatNumber,
  formatFloat,
  sanitizeText,
  toISODate,
  formatDisplayDate,
  formatTimestampDisplay,
} from "./utils.js";
import {
  SECTION_NAV_ITEMS,
  SEARCH_RESULT_LIMIT,
  ONBOARDING_STEPS,
} from "./appConstants.js";
import {
  setStatusCallback,
  updateStatus,
  getDatasetEntries,
  setDatasetEntries,
  setDatasetAnalytics,
  getDatasetAnalytics,
  setDatasetLabel,
  getDatasetLabel,
  setCurrentRange,
  getCurrentRange,
  setCustomRange,
  getCustomRange,
  saveChatDataset,
  listChatDatasets,
  getChatDatasetById,
  setActiveChatId,
  getActiveChatId,
  addSavedView,
  getSavedViews,
  updateSavedView,
  removeSavedView,
  clearSavedViews,
  setCompareSelection,
  getCompareSelection,
  getSearchState,
  getHourlyState,
  updateHourlyState,
  resetHourlyFilters,
  getWeekdayState,
  updateWeekdayState,
  getCachedAnalytics,
  setCachedAnalytics,
  clearAnalyticsCache,
  setDatasetFingerprint,
  getDatasetFingerprint,
  setDatasetParticipantDirectory,
  resetWeekdayFilters,
  computeDatasetFingerprint,
} from "./state.js";
import {
  formatHourLabel,
  computeTimeOfDayDataset,
} from "./analytics/activity.js";
import { createSearchController } from "./search.js";
import { createSavedViewsController } from "./savedViews.js";
import {
  API_BASE,
  BRAND_NAME,
  RELAY_SERVICE_NAME,
  STATUS_AUTO_HIDE_DELAY_MS,
  STATUS_EXIT_DURATION_MS,
  motionPreferenceQuery,
  initialReduceMotionPreferred,
} from "./config.js";
import { EXPORT_THEME_STYLES } from "./theme.js";
import {
  createDatasetEmptyStateManager,
  createCompactModeManager,
  createAccessibilityController,
} from "./ui.js";
import {
  createAppDomRefs,
  createAnalyticsRequestTracker,
  setupAppBootstrap,
  createExportRuntime,
  createExportFilterSummary,
  createRelayRuntime,
  createDashboardRuntime,
  createDatasetLifecycleRuntime,
  createOnboardingController,
  createStatusUiController,
  createThemeUiController,
  createSectionNavController,
  createChatSelectionController,
  createRangeFiltersController,
  createAnalyticsPipeline,
  createKeyboardShortcutsController,
  createDataStatusController,
  createParticipantInteractionsController,
  createBusyRuntimeController,
  fetchJson,
  formatRelayAccount,
  COMPACT_STORAGE_KEY,
  REDUCE_MOTION_STORAGE_KEY,
  HIGH_CONTRAST_STORAGE_KEY,
  initWindowToasts,
} from "./appShell/index.js";

const {
  statusEl,
  relayBannerEl,
  relayBannerMessage,
  relayBannerMeta,
  relayOnboardingSteps,
  summaryEl,
  participantsBody,
  participantsNote,
  participantsTopSelect,
  participantsSortSelect,
  participantsTimeframeSelect,
  participantPresetButtons,
  rangeSelect,
  chatSelector,
  relayStatusEl,
  relayAccountEl,
  relayStartButton,
  relayStopButton,
  relayLogoutButton,
  relayReloadAllButton,
  relayClearStorageButton,
  relayQrContainer,
  relayQrImage,
  relayHelpText,
  relaySyncProgressEl,
  relaySyncChatsMeta,
  relaySyncMessagesMeta,
  reduceMotionToggle,
  highContrastToggle,
  customControls,
  customStartInput,
  customEndInput,
  customApplyButton,
  hourlyTopHourEl,
  brushSummaryEl,
  filterNoteEl,
  hourlyChartEl,
  hourlyAnomaliesEl,
  dailyChartEl,
  dailyAvgDayEl,
  weeklyChartEl,
  weeklyCumulativeEl,
  weeklyRollingEl,
  weeklyAverageEl,
  weekdayChartEl,
  weekdayFilterNote,
  weekdayToggleWeekdays,
  weekdayToggleWeekends,
  weekdayToggleWorking,
  weekdayToggleOffhours,
  weekdayHourStartInput,
  weekdayHourEndInput,
  messageTypeSummaryEl,
  messageTypeNoteEl,
  downloadPdfButton,
  downloadTimeOfDayButton,
  downloadParticipantsButton,
  downloadHourlyButton,
  downloadDailyButton,
  downloadWeeklyButton,
  downloadWeekdayButton,
  downloadMessageTypesButton,
  downloadSentimentButton,
  downloadChatJsonButton,
  sentimentSummaryEl,
  sentimentTrendNote,
  sentimentDailyChart,
  sentimentPositiveList,
  sentimentNegativeList,
  savedViewNameInput,
  saveViewButton,
  savedViewList,
  applySavedViewButton,
  deleteSavedViewButton,
  savedViewGallery,
  compareViewASelect,
  compareViewBSelect,
  compareViewsButton,
  compareSummaryEl,
  searchForm,
  searchKeywordInput,
  searchParticipantSelect,
  searchStartInput,
  searchEndInput,
  resetSearchButton,
  downloadSearchButton,
  searchResultsSummary,
  searchResultsList,
  searchInsightsEl,
  searchProgressEl,
  searchProgressTrack,
  searchProgressBar,
  searchProgressLabel,
  highlightList,
  downloadMarkdownButton,
  downloadSlidesButton,
  logDrawerToggleButton,
  logDrawerEl,
  logDrawerCloseButton,
  logDrawerClearButton,
  logDrawerList,
  logDrawerConnectionLabel,
  globalProgressEl,
  globalProgressLabel,
  toastContainer,
  compactToggleButton,
  onboardingOverlay,
  onboardingCopyEl,
  onboardingStepLabel,
  onboardingSkipButton,
  onboardingNextButton,
  heroStatusBadge,
  heroStatusCopy,
  datasetEmptyCallout,
  datasetEmptyHeading,
  datasetEmptyCopy,
  sectionNavInner,
  timeOfDayWeekdayToggle,
  timeOfDayWeekendToggle,
  timeOfDayHourStartInput,
  timeOfDayHourEndInput,
  timeOfDayHourStartLabel,
  timeOfDayHourEndLabel,
  timeOfDaySparklineEl,
  timeOfDayBandsEl,
  timeOfDayCalloutsEl,
  timeOfDayChartContainer,
  pollsNote,
  pollsTotalEl,
  pollsCreatorsEl,
  pollsListEl,
  dashboardRoot,
  themeToggleInputs,
} = createAppDomRefs();

const datasetEmptyStateManager = createDatasetEmptyStateManager({
  calloutEl: datasetEmptyCallout,
  headingEl: datasetEmptyHeading,
  copyEl: datasetEmptyCopy,
  buttons: [
    downloadPdfButton,
    downloadMarkdownButton,
    downloadSlidesButton,
    downloadChatJsonButton,
    downloadParticipantsButton,
    downloadHourlyButton,
    downloadDailyButton,
    downloadWeeklyButton,
    downloadWeekdayButton,
    downloadTimeOfDayButton,
    downloadMessageTypesButton,
    downloadSentimentButton,
    downloadSearchButton,
  ],
});
const setDatasetEmptyMessage = datasetEmptyStateManager.setMessage;
const chatSelectionController = createChatSelectionController({
  chatSelector,
  brandName: BRAND_NAME,
  formatNumber,
  formatDisplayDate,
  listChatDatasets,
  getActiveChatId,
  setActiveChatId,
});
const {
  encodeChatSelectorValue,
  setRemoteChatList,
  getRemoteChatList,
  getRemoteChatsLastFetchedAt,
  refreshChatSelector,
  handleChatSelectionChange: handleChatSelectionChangeCore,
} = chatSelectionController;
const analyticsRequestTracker = createAnalyticsRequestTracker();
let dashboardRenderController = null;
function renderDashboard(analytics) {
  dashboardRenderController?.renderDashboard(analytics);
}
function renderParticipants(analytics) {
  dashboardRenderController?.renderParticipants(analytics);
}
function ensureWeekdayDayFilters() {
  dashboardRenderController?.ensureWeekdayDayFilters();
}
function ensureWeekdayHourFilters() {
  dashboardRenderController?.ensureWeekdayHourFilters();
}
function syncWeekdayControlsWithState() {
  dashboardRenderController?.syncWeekdayControlsWithState();
}
function rerenderHourlyFromState() {
  dashboardRenderController?.rerenderHourlyFromState();
}
function rerenderWeekdayFromState() {
  dashboardRenderController?.rerenderWeekdayFromState();
}
function ensureDayFilters() {
  dashboardRenderController?.ensureDayFilters();
}
function ensureHourFilters() {
  dashboardRenderController?.ensureHourFilters();
}
function syncHourlyControlsWithState() {
  dashboardRenderController?.syncHourlyControlsWithState();
}
const analyticsPipeline = createAnalyticsPipeline();
const { computeAnalyticsWithWorker } = analyticsPipeline;
const rangeFiltersController = createRangeFiltersController({
  elements: {
    rangeSelect,
    customControls,
    customStartInput,
    customEndInput,
    customApplyButton,
    searchStartInput,
    searchEndInput,
  },
  deps: {
    getDatasetEntries,
    getDatasetLabel,
    setCurrentRange,
    setCustomRange,
    getCustomRange,
    getCachedAnalytics,
    setCachedAnalytics,
    setDatasetAnalytics,
    renderDashboard,
    computeAnalyticsWithWorker,
    updateStatus,
    formatNumber,
    formatDisplayDate,
    getTimestamp,
    toISODate,
    onRangeApplied: syncHeroPillsWithRange,
    nextAnalyticsRequestToken: analyticsRequestTracker.nextToken,
    isAnalyticsRequestCurrent: analyticsRequestTracker.isCurrent,
  },
});
const {
  normalizeRangeValue,
  filterEntriesByRange,
  describeRange,
  showCustomControls,
  updateCustomRangeBounds,
  applyRangeAndRender,
  handleRangeChange,
  applyCustomRange,
} = rangeFiltersController;

const searchController = createSearchController({
  elements: {
    form: searchForm,
    keywordInput: searchKeywordInput,
    participantSelect: searchParticipantSelect,
    startInput: searchStartInput,
    endInput: searchEndInput,
    resetButton: resetSearchButton,
    resultsSummaryEl: searchResultsSummary,
    resultsListEl: searchResultsList,
    insightsEl: searchInsightsEl,
    progressEl: searchProgressEl,
    progressTrackEl: searchProgressTrack,
    progressBarEl: searchProgressBar,
    progressLabelEl: searchProgressLabel,
  },
  options: { resultLimit: SEARCH_RESULT_LIMIT },
});

const savedViewsController = createSavedViewsController({
  elements: {
    nameInput: savedViewNameInput,
    saveButton: saveViewButton,
    listSelect: savedViewList,
    applyButton: applySavedViewButton,
    deleteButton: deleteSavedViewButton,
    gallery: savedViewGallery,
    compareSelectA: compareViewASelect,
    compareSelectB: compareViewBSelect,
    compareButton: compareViewsButton,
    compareSummaryEl,
    rangeSelect,
    customStartInput,
    customEndInput,
  },
  dependencies: {
    getDatasetEntries,
    getDatasetAnalytics,
    getDatasetLabel,
    getCurrentRange,
    getCustomRange,
    setCurrentRange,
    setCustomRange,
    showCustomControls,
    addSavedView,
    getSavedViews,
    updateSavedView,
    removeSavedView,
    clearSavedViews,
    getCompareSelection,
    setCompareSelection,
    getHourlyState,
    updateHourlyState,
    getWeekdayState,
    updateWeekdayState,
    applyRangeAndRender,
    ensureDayFilters,
    ensureHourFilters,
    syncHourlyControlsWithState,
    ensureWeekdayDayFilters,
    ensureWeekdayHourFilters,
    syncWeekdayControlsWithState,
    describeRange,
    updateStatus,
    filterEntriesByRange,
    normalizeRangeValue,
  },
});
const dataStatusController = createDataStatusController({
  elements: {
    dashboardRoot,
    heroStatusBadge,
    heroStatusCopy,
    datasetEmptyStateManager,
  },
  deps: {
    setDatasetEmptyMessage,
    savedViewsController,
    formatRelayAccount,
    formatNumber,
  },
});
const {
  setDashboardLoadingState,
  setDataAvailabilityState,
  updateHeroRelayStatus,
  getDataAvailable,
} = dataStatusController;
setDashboardLoadingState(true);
document.querySelectorAll(".summary-value").forEach(element => {
  element.setAttribute("data-skeleton", "value");
});

const participantFilters = {
  topCount: Number(participantsTopSelect?.value ?? 25) || 0,
  sortMode: participantsSortSelect?.value ?? "most",
  timeframe: participantsTimeframeSelect?.value ?? "all",
};
const participantInteractionsController = createParticipantInteractionsController({
  elements: {
    participantsTopSelect,
    participantsSortSelect,
    participantsTimeframeSelect,
    participantsBody,
  },
  deps: {
    participantFilters,
    getDatasetAnalytics,
    renderParticipants,
  },
});
const {
  handleParticipantsTopChange,
  handleParticipantsSortChange,
  handleParticipantsTimeframeChange,
  handleParticipantPresetClick,
  handleParticipantRowToggle,
} = participantInteractionsController;

const getExportFilterSummary = createExportFilterSummary({
  normalizeRangeValue,
  getCurrentRange,
  describeRange,
  participantFilters,
});
const { controller: dashboardRuntimeController, getParticipantView } = createDashboardRuntime({
  elements: {
    summaryEl,
    participantsBody,
    participantsNote,
    participantPresetButtons,
    hourlyChartEl,
    filterNoteEl,
    brushSummaryEl,
    hourlyAnomaliesEl,
    hourlyTopHourEl,
    dailyChartEl,
    dailyAvgDayEl,
    weeklyChartEl,
    weeklyCumulativeEl,
    weeklyRollingEl,
    weeklyAverageEl,
    weekdayChartEl,
    weekdayFilterNote,
    weekdayToggleWeekdays,
    weekdayToggleWeekends,
    weekdayToggleWorking,
    weekdayToggleOffhours,
    weekdayHourStartInput,
    weekdayHourEndInput,
    timeOfDayWeekdayToggle,
    timeOfDayWeekendToggle,
    timeOfDayHourStartInput,
    timeOfDayHourEndInput,
    timeOfDayHourStartLabel,
    timeOfDayHourEndLabel,
    timeOfDayChartContainer,
    timeOfDaySparklineEl,
    timeOfDayBandsEl,
    timeOfDayCalloutsEl,
    sentimentSummaryEl,
    sentimentTrendNote,
    sentimentDailyChart,
    sentimentPositiveList,
    sentimentNegativeList,
    messageTypeSummaryEl,
    messageTypeNoteEl,
    pollsListEl,
    pollsTotalEl,
    pollsCreatorsEl,
    pollsNote,
    highlightList,
    rangeSelect,
  },
  deps: {
    getDatasetLabel,
    getDatasetEntries,
    getDatasetAnalytics,
    getCustomRange,
    getHourlyState,
    updateHourlyState,
    getWeekdayState,
    updateWeekdayState,
    participantFilters,
    setDataAvailabilityState,
    searchPopulateParticipants: () => searchController.populateParticipants(),
    searchRenderResults: () => searchController.renderResults(),
    applyCustomRange,
    formatNumber,
    formatFloat,
    sanitizeText,
  },
});
dashboardRenderController = dashboardRuntimeController;
const themeUiController = createThemeUiController({
  themeToggleInputs,
  mediaQuery: window.matchMedia ? window.matchMedia("(prefers-color-scheme: dark)") : null,
  exportThemeStyles: EXPORT_THEME_STYLES,
});
const { initThemeControls, getExportThemeConfig } = themeUiController;

const {
  exportParticipants,
  exportHourly,
  exportDaily,
  exportWeekly,
  exportWeekday,
  exportTimeOfDay,
  exportMessageTypes,
  exportChatJson,
  exportSentiment,
  exportSearchResults,
  handleDownloadMarkdownReport,
  handleDownloadSlidesReport,
  exportMessageSubtype,
  handleDownloadPdfReport,
} = createExportRuntime({
  brandName: BRAND_NAME,
  getExportFilterSummary,
  getExportThemeConfig,
  getDatasetFingerprint,
  getDatasetAnalytics,
  getDatasetEntries,
  getDatasetLabel,
  getCurrentRange,
  getParticipantView,
  getSearchState,
  updateStatus,
  formatNumber,
  formatFloat,
  formatTimestampDisplay,
  computeTimeOfDayDataset,
  formatHourLabel,
  describeRange,
  filterEntriesByRange,
  normalizeRangeValue,
});
const { applyEntriesToApp } = createDatasetLifecycleRuntime({
  rangeSelect,
  deps: {
    setDatasetEntries,
    setDatasetFingerprint,
    setDatasetParticipantDirectory,
    clearAnalyticsCache,
    setDatasetLabel,
    setCurrentRange,
    setCustomRange,
    resetHourlyFilters,
    resetWeekdayFilters,
    computeDatasetFingerprint,
    saveChatDataset,
    setCachedAnalytics,
    setDatasetAnalytics,
    setActiveChatId,
    computeAnalyticsWithWorker,
    renderDashboard,
    updateCustomRangeBounds,
    encodeChatSelectorValue,
    refreshChatSelector,
    updateStatus,
    setDashboardLoadingState,
    formatNumber,
    nextAnalyticsRequestToken: analyticsRequestTracker.nextToken,
    isAnalyticsRequestCurrent: analyticsRequestTracker.isCurrent,
    resetSavedViewsForNewDataset: () => savedViewsController.resetForNewDataset(),
    resetSearchState: () => searchController.resetState(),
    populateSearchParticipants: () => searchController.populateParticipants(),
  },
});
const busyRuntimeController = createBusyRuntimeController({
  globalProgressEl,
  globalProgressLabel,
});
const { withGlobalBusy } = busyRuntimeController;

const {
  startRelaySession,
  stopRelaySession,
  syncRelayChats,
  loadRemoteChat,
  isLogDrawerOpen,
  openLogDrawer,
  closeLogDrawer,
  initRelayControls,
} = createRelayRuntime({
  relayElements: {
    relayStartButton,
    relayStopButton,
    relayLogoutButton,
    relayReloadAllButton,
    relayStatusEl,
    relayAccountEl,
    relayQrContainer,
    relayQrImage,
    relayHelpText,
    relayBannerEl,
    relayBannerMessage,
    relayBannerMeta,
    relayOnboardingSteps,
    logDrawerToggleButton,
    logDrawerEl,
    logDrawerList,
    logDrawerConnectionLabel,
    relayClearStorageButton,
    relaySyncProgressEl,
    relaySyncChatsMeta,
    relaySyncMessagesMeta,
  },
  relayHelpers: {
    updateStatus,
    withGlobalBusy,
    fetchJson,
    setRemoteChatList,
    getRemoteChatList,
    getRemoteChatsLastFetchedAt,
    refreshChatSelector,
    setDashboardLoadingState,
    setDatasetEmptyMessage,
    setDataAvailabilityState,
    updateHeroRelayStatus,
    applyEntriesToApp,
    encodeChatSelectorValue,
  },
  electronAPI: window.electronAPI,
  bootstrapElements: {
    relayStartButton,
    relayStatusEl,
    relayStopButton,
    relayLogoutButton,
    relayReloadAllButton,
    relayClearStorageButton,
    logDrawerToggleButton,
    logDrawerCloseButton,
    logDrawerClearButton,
  },
  fetchJson,
  apiBase: API_BASE,
  setRemoteChatList,
  refreshChatSelector,
  updateStatus,
});
initWindowToasts();
const statusUiController = createStatusUiController({
  statusEl,
  toastContainer,
  autoHideDelayMs: STATUS_AUTO_HIDE_DELAY_MS,
  exitDurationMs: STATUS_EXIT_DURATION_MS,
});
const {
  showToast,
  showStatusMessage,
} = statusUiController;
const sectionNavController = createSectionNavController({
  containerEl: sectionNavInner,
  navItemsConfig: SECTION_NAV_ITEMS,
});
const { buildSectionNav, setupSectionNavTracking } = sectionNavController;

const { apply: applyCompactMode, init: initCompactMode } = createCompactModeManager({
  toggle: compactToggleButton,
  storageKey: COMPACT_STORAGE_KEY,
  showToast,
});

const accessibilityController = createAccessibilityController({
  reduceMotionToggle,
  highContrastToggle,
  motionPreferenceQuery,
  initialReduceMotionPreferred,
  showToast,
  reduceMotionStorageKey: REDUCE_MOTION_STORAGE_KEY,
  highContrastStorageKey: HIGH_CONTRAST_STORAGE_KEY,
});
const { initAccessibilityControls } = accessibilityController;

const onboardingController = createOnboardingController({
  overlayEl: onboardingOverlay,
  copyEl: onboardingCopyEl,
  stepLabelEl: onboardingStepLabel,
  nextButtonEl: onboardingNextButton,
  steps: ONBOARDING_STEPS,
});

function syncHeroPillsWithRange() { }

async function handleChatSelectionChange(event) {
  return handleChatSelectionChangeCore(event, {
    getChatDatasetById,
    applyEntriesToApp,
    loadRemoteChat,
    updateStatus,
  });
}

const keyboardShortcutsController = createKeyboardShortcutsController({
  deps: {
    syncRelayChats,
    isLogDrawerOpen,
    closeLogDrawer,
    openLogDrawer,
    applyCompactMode,
    showToast,
    onboardingController,
  },
});
const { initKeyboardShortcuts } = keyboardShortcutsController;
setupAppBootstrap({
  status: {
    setStatusCallback,
    statusEl,
    showStatusMessage,
    showToast,
  },
  keyboardShortcuts: {
    initKeyboardShortcuts,
  },
  eventBindings: {
    elements: {
      chatSelector,
      rangeSelect,
      customApplyButton,
      customStartInput,
      customEndInput,
      downloadParticipantsButton,
      downloadHourlyButton,
      downloadDailyButton,
      downloadWeeklyButton,
      downloadWeekdayButton,
      downloadTimeOfDayButton,
      downloadMessageTypesButton,
      downloadChatJsonButton,
      downloadSentimentButton,
      downloadMarkdownButton,
      downloadSlidesButton,
      downloadSearchButton,
      downloadPdfButton,
      participantsTopSelect,
      participantsSortSelect,
      participantsTimeframeSelect,
      participantPresetButtons,
      participantsBody,
      weekdayToggleWeekdays,
      weekdayToggleWeekends,
      weekdayToggleWorking,
      weekdayToggleOffhours,
      timeOfDayWeekdayToggle,
      timeOfDayWeekendToggle,
      timeOfDayHourStartInput,
      timeOfDayHourEndInput,
      weekdayHourStartInput,
      weekdayHourEndInput,
    },
    handlers: {
      handleChatSelectionChange,
      handleRangeChange,
      exportParticipants,
      exportHourly,
      exportDaily,
      exportWeekly,
      exportWeekday,
      exportTimeOfDay,
      exportMessageTypes,
      exportChatJson,
      exportSentiment,
      exportMessageSubtype,
      handleDownloadMarkdownReport,
      handleDownloadSlidesReport,
      exportSearchResults,
      handleDownloadPdfReport,
      handleParticipantsTopChange,
      handleParticipantsSortChange,
      handleParticipantsTimeframeChange,
      handleParticipantPresetClick,
      handleParticipantRowToggle,
    },
    deps: {
      updateStatus,
      applyCustomRange,
      updateWeekdayState,
      ensureWeekdayDayFilters,
      rerenderWeekdayFromState,
      ensureWeekdayHourFilters,
      updateHourlyState,
      getHourlyState,
      ensureDayFilters,
      syncHourlyControlsWithState,
      rerenderHourlyFromState,
    },
  },
  bootstrap: {
    elements: {
      onboardingSkipButton,
      onboardingNextButton,
    },
    deps: {
      initRelayControls,
      initThemeControls,
      initCompactMode,
      initAccessibilityControls,
      setDataAvailabilityState,
      onboardingController,
      startRelaySession,
      stopRelaySession,
      buildSectionNav,
      setupSectionNavTracking,
      searchController,
      savedViewsController,
      getDataAvailable,
      refreshChatSelector,
      updateStatus,
      relayServiceName: RELAY_SERVICE_NAME,
      prefersReducedMotion: () => accessibilityController.prefersReducedMotion(),
    },
  },
});
