import { formatNumber, formatFloat } from "./utils.js";
import { BRAND_NAME } from "./config.js";
import { collectExportSummary, escapeHtml } from "./exportSummary.js";
import { buildExportDeckCss, buildExportDeckMarkup } from "./exportDeck.js";

export function buildMarkdownReport({
  analytics,
  theme,
  datasetLabel,
  filterDetails = [],
  brandName = BRAND_NAME,
}) {
  const nowIso = new Date().toISOString();
  const title = datasetLabel || `${brandName} Chat`;
  const details = collectExportSummary(analytics);
  const highlights = details.highlights;
  const topSenders = details.topSenders;
  const messageTypeSummary = analytics.message_types?.summary || [];
  const systemSummary = details.systemSummary;
  const weeklySummary = details.weeklySummary;

  const lines = [];
  lines.push(`# ${title} – Conversation summary`);
  lines.push(`_${theme?.tagline || `Insights prepared by ${brandName}.`}_`);
  lines.push(`*Created ${nowIso} · Styled with the ${theme?.label || "Aurora"} theme*`);
  if (details.rangeLabel) {
    lines.push("");
    lines.push(`> **Date range:** ${details.rangeLabel}`);
  }
  if (filterDetails.length) {
    lines.push(`> **Filters:** ${filterDetails.join(" · ")}`);
  }
  lines.push(`> **Report style:** ${theme?.label || "Default"}`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Quick glance");
  if (details.overviewItems.length) {
    details.overviewItems.forEach(item => lines.push(`- ${item}`));
  } else {
    lines.push("- Load a dataset to populate this section.");
  }
  lines.push("");
  lines.push("## Highlights");
  if (highlights.length) {
    highlights.forEach(item => lines.push(`- **${item.label}:** ${item.value} ${item.descriptor || ""}`));
  } else {
    lines.push("- Highlights will appear once enough activity is available.");
  }
  lines.push("");
  lines.push("## Top participants");
  if (topSenders.length) {
    topSenders.slice(0, 10).forEach((entry, idx) => {
      lines.push(
        `${idx + 1}. **${entry.sender}** — ${formatNumber(entry.count)} messages${
          entry.share ? ` (${formatFloat(entry.share * 100, 1)}%)` : ""
        }`,
      );
    });
  } else {
    lines.push("- No participants fit the current filters.");
  }
  lines.push("");
  lines.push("## Message types");
  if (messageTypeSummary.length) {
    messageTypeSummary.forEach(entry => {
      lines.push(
        `- ${entry.group}: ${entry.type} — ${formatNumber(entry.count)} (${formatFloat(
          (entry.share || 0) * 100,
          1,
        )}%)`,
      );
    });
  } else {
    lines.push("- Provide message type data to populate this section.");
  }
  lines.push("");
  lines.push("## System events");
  systemSummary &&
    lines.push(
      [
        `Joins: ${formatNumber(systemSummary.joins || 0)}`,
        `Added: ${formatNumber(systemSummary.added || 0)}`,
        `Left: ${formatNumber(systemSummary.left || 0)}`,
        `Removed: ${formatNumber(systemSummary.removed || 0)}`,
        `Changed: ${formatNumber(systemSummary.changed || 0)}`,
      ].join(" · "),
    );
  lines.push("");
  lines.push("## Weekly recap");
  if (weeklySummary.latestDeltaPercent !== null && weeklySummary.latestDeltaPercent !== undefined) {
    const percent = formatFloat(Math.abs(weeklySummary.latestDeltaPercent) * 100, 1);
    const direction = weeklySummary.latestDeltaPercent > 0 ? "increase" : "decrease";
    lines.push(`- Activity shows a ${direction} of ${percent}% compared to the previous week.`);
  } else {
    lines.push("- Weekly data will appear once you're synced.");
  }
  lines.push("");
  lines.push(`_Generated by ${brandName}_`);
  return lines.join("\n");
}

export function buildSlidesHtml({
  analytics,
  theme,
  datasetLabel,
  filterDetails,
  brandName,
}) {
  const exportBrand = brandName || BRAND_NAME;
  const styles = buildExportDeckCss(theme, { mode: "screen" });
  const deckMarkup = buildExportDeckMarkup({
    analytics,
    theme,
    datasetLabel,
    filterDetails,
    brandName: exportBrand,
    mode: "screen",
  });
  const title = escapeHtml(`${datasetLabel || "ChatScope conversation report"}`);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${title} – Slides</title>
  <style>${styles}</style>
</head>
<body>
${deckMarkup}
</body>
</html>`;
}

export function buildPdfDocumentHtml({
  analytics,
  theme,
  datasetLabel,
  filterDetails,
  brandName,
}) {
  const exportBrand = brandName || BRAND_NAME;
  const title = escapeHtml(`${datasetLabel || "ChatScope conversation"} – PDF`);
  const styles = buildExportDeckCss(theme, { mode: "print" });
  const deckMarkup = buildExportDeckMarkup({
    analytics,
    theme,
    datasetLabel,
    filterDetails,
    brandName: exportBrand,
    mode: "print",
  });
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${title}</title>
  <style>${styles}</style>
</head>
<body>
${deckMarkup}
</body>
</html>`;
}
