export const UI_COPY = {
  relay: {
    offlineStatus: "Relay offline.",
    offlineHero: "Start relay.",
    offlineMeta: "Workspace locked.",
    offlineNextStep: "Start relay.",
    startingStatus: "Starting relay.",
    startingHero: "Starting relay.",
    startingMeta: "Preparing workspace.",
    waitingPhoneStatus: "Link your phone.",
    waitingPhoneHero: "Scan the QR code.",
    waitingPhoneFallbackHero: "Start relay to get a QR code.",
    waitingPhoneMeta: "Waiting for phone link.",
    runningLoadingHero: "Loading chats.",
    runningRefreshingHero: chatCount => `${chatCount} chats loaded. Refreshing.`,
    runningRefreshingMeta: chatCount => `Refreshing · ${chatCount} chats loaded`,
    runningLoadingMeta: "Workspace opens when chats load.",
    runningEmptyHero: "No chats loaded.",
    runningEmptyMeta: "This account has no chats yet.",
    runningReadyHero: chatCount => `${chatCount} chats ready.`,
    runningReadyMeta: lastUpdated => `Updated ${lastUpdated}`,
    runningReadyBannerFallback: "Ready.",
    banner: {
      offlineMeta: "Workspace locked until relay starts.",
      startingMeta: "Preparing workspace.",
      waitingMeta: "Waiting for QR scan.",
      loadingMeta: "Chats are still loading.",
      emptyMeta: "No chats available yet.",
      noChatMeta: "Choose a chat to begin.",
    },
    onboarding: {
      startPending: "Open WAAN Relay.",
      startActive: "Starting relay.",
      startComplete: "Relay running.",
      startError: "Couldn't start relay.",
      qrPending: "Open Linked Devices.",
      qrActive: "Scan the QR code.",
      qrComplete: "Phone linked.",
      syncPending: "Chats load here.",
      syncActive: "Loading chats.",
      syncComplete: "Chats loaded.",
    },
    firstRun: {
      openRelay: "Open relay",
      startRelay: "Start relay",
      starting: "Starting…",
      waitingPhone: "Link phone",
      loadingChats: "Loading chats",
      noChats: "No chats yet",
      chooseChat: "Pick a chat",
    },
    primaryAction: {
      startLabel: "Start relay",
      startHint: "Open the relay app.",
      reconnectLabel: "Reconnect relay",
      reconnectHint: "Restart the relay.",
      resyncLabel: "Refresh chats",
      resyncHint: "Fetch the latest chats.",
      waitingLabel: "Link your phone",
      waitingHint: "Open Linked Devices.",
      startingLabel: "Starting…",
      startingHint: relayServiceName => `Starting ${relayServiceName}…`,
    },
  },
  dataset: {
    emptyHeading: "Pick a chat",
    emptyMessage: "Choose one from Loaded chats.",
    noChatsLoaded: "No chats loaded yet",
    offlineHeading: "Workspace locked",
    offlineMessage: "Start relay to unlock chat and range controls.",
    waitingHeading: "Setup in progress",
    waitingMessage: "Chats appear here after you link your phone.",
    loadingHeading: "Loading chats",
    loadingMessage: "Chat and range controls unlock once chats finish loading.",
    noChatsHeading: "No chats loaded",
    noChatsMessage: "This linked account has no chats yet.",
    readyHeading: "Pick a chat",
    readyMessage: "Choose one from Loaded chats.",
  },
  savedViews: {
    noDataPlaceholder: "Pick a chat",
    emptyTitle: "No saved views",
    emptyMessage: "Save this view.",
    noDataTitle: "Pick a chat",
    noDataMessage: "Save views after you pick a chat.",
    selectPlaceholder: "Choose a saved view…",
    comparePrompt: "Pick two views.",
    compareNeedMore: "Save one more view.",
    compareStart: "Save a view to compare.",
    compareRetry: "Re-save these views.",
  },
  search: {
    noDataStatus: "Pick a chat before searching.",
    noDataError: "Pick a chat and try again.",
    panelTitle: "Search",
    panelPrompt: "Add a keyword, person, or date.",
    noMatchesTitle: "No matches",
    noMatchesMessage: "Try another keyword or date.",
    progressMessage: "Scanning messages.",
    clearedStatus: "Search filters cleared.",
    errorStatus: "Search failed.",
    errorMessage: "Search failed. Try again.",
    emptySummary: "Search this chat.",
    noMatchesSummary: "No matches.",
    noMessagesSummary: "No messages in this chat yet.",
    allMessagesSummary: countLabel => `All ${countLabel} messages.`,
    limitedSummary: (shownLabel, totalLabel) => `Showing ${shownLabel} of ${totalLabel} matches.`,
    matchesSummary: (count, countLabel) => `Showing ${countLabel} match${count === 1 ? "" : "es"}.`,
  },
  analytics: {
    noData: "No data in this range.",
    noHourlyData: "No hourly data in this range.",
    noTimeOfDayData: "No time-of-day data in this range.",
    noWeekdayData: "No weekday data in this range.",
    noMessageTypes: "No message types in this range.",
    noPolls: "No polls in this range.",
    noHighlights: "Highlights appear after chats load.",
    noGenericData: "No data available.",
  },
  relayLog: {
    title: "Diagnostics and relay log",
    help: "Use this when sync stalls or reconnect fails.",
    connectionConnecting: "Connecting…",
    connectionLive: "Live relay log",
    connectionUnavailable: "Live log stream unavailable here.",
    connectionRetrying: "Log stream disconnected. Retrying…",
    empty: "No relay events yet.",
    exportLabel: "Export diagnostics",
    exportTitle: "Download a diagnostics bundle for support or bug reports.",
    reportLabel: "Report issue",
    reportTitle: "Open a prefilled issue report using the latest diagnostics snapshot.",
    clearLabel: "Clear log",
    clearTitle: "Clear the visible relay log history.",
    closeLabel: "Close",
    closeTitle: "Close diagnostics and return to the workspace.",
    clearError: "Couldn't clear the relay log.",
    exportSuccess: "Downloaded diagnostics bundle.",
    exportError: "Couldn't export diagnostics bundle.",
    reportSuccess: "Opened prefilled issue report.",
    reportError: "Couldn't open prefilled issue report.",
  },
};
