export const UI_COPY = {
  relay: {
    offlineStatus: "Relay offline.",
    offlineHero: "Start relay.",
    offlineMeta: "Waiting.",
    offlineNextStep: "Start relay.",
    startingStatus: "Starting relay.",
    startingHero: "Starting relay.",
    startingMeta: "Starting.",
    waitingPhoneStatus: "Link your phone.",
    waitingPhoneHero: "Scan the QR code.",
    waitingPhoneFallbackHero: "Start relay to get a QR code.",
    waitingPhoneMeta: "Waiting for phone link.",
    runningLoadingHero: "Loading chats.",
    runningRefreshingHero: chatCount => `${chatCount} chats loaded. Refreshing.`,
    runningRefreshingMeta: chatCount => `Refreshing · ${chatCount} chats loaded`,
    runningLoadingMeta: "Loading chats.",
    runningReadyHero: chatCount => `${chatCount} chats ready.`,
    runningReadyMeta: lastUpdated => `Updated ${lastUpdated}`,
    runningReadyBannerFallback: "Ready.",
    onboarding: {
      startPending: "Open WAAN Relay.",
      startActive: "Starting relay.",
      startComplete: "Relay running.",
      startError: "Couldn't start relay.",
      qrPending: "Open Linked Devices.",
      qrActive: "Scan the QR code.",
      qrComplete: "Phone linked.",
      syncPending: "Chats load here.",
      syncActive: "Loading chats.",
      syncComplete: "Chats loaded.",
    },
    firstRun: {
      openRelay: "Open relay",
      startRelay: "Start relay",
      starting: "Starting…",
      waitingPhone: "Link your phone",
      loadingChats: "Loading chats",
      chooseChat: "Choose chat",
    },
    primaryAction: {
      startLabel: "Start relay",
      startHint: "Open the relay app.",
      reconnectLabel: "Reconnect relay",
      reconnectHint: "Restart the relay.",
      resyncLabel: "Refresh chats",
      resyncHint: "Fetch the latest chats.",
      waitingLabel: "Link your phone",
      waitingHint: "Open Linked Devices.",
      startingLabel: "Starting…",
      startingHint: relayServiceName => `Starting ${relayServiceName}…`,
    },
  },
  dataset: {
    emptyHeading: "No chat selected",
    emptyMessage: "Pick a chat.",
    noChatsLoaded: "No chats loaded yet",
    offlineHeading: "Start relay",
    offlineMessage: "Then link your phone.",
    waitingHeading: "Waiting for chats",
    waitingMessage: "They appear here after linking.",
    readyHeading: "Pick a chat",
    readyMessage: "Choose one from Loaded chats.",
  },
  savedViews: {
    noDataPlaceholder: "Pick a chat",
    emptyTitle: "No saved views",
    emptyMessage: "Save this view.",
    noDataTitle: "Pick a chat",
    noDataMessage: "Save views after you pick a chat.",
    selectPlaceholder: "Choose a saved view…",
    comparePrompt: "Pick two views.",
    compareNeedMore: "Save one more view.",
    compareStart: "Save a view to compare.",
    compareRetry: "Re-save these views.",
  },
  search: {
    noDataStatus: "Pick a chat before searching.",
    noDataError: "Pick a chat and try again.",
    panelTitle: "Search",
    panelPrompt: "Add a keyword, person, or date.",
    noMatchesTitle: "No matches",
    noMatchesMessage: "Try another keyword or date.",
    progressMessage: "Scanning messages.",
    clearedStatus: "Search filters cleared.",
    errorStatus: "Search failed.",
    errorMessage: "Search failed. Try again.",
    emptySummary: "Search this chat.",
    noMatchesSummary: "No matches.",
    noMessagesSummary: "No messages in this chat yet.",
    allMessagesSummary: countLabel => `All ${countLabel} messages.`,
    limitedSummary: (shownLabel, totalLabel) => `Showing ${shownLabel} of ${totalLabel} matches.`,
    matchesSummary: (count, countLabel) => `Showing ${countLabel} match${count === 1 ? "" : "es"}.`,
  },
  analytics: {
    noData: "No data in this range.",
    noHourlyData: "No hourly data in this range.",
    noTimeOfDayData: "No time-of-day data in this range.",
    noWeekdayData: "No weekday data in this range.",
    noMessageTypes: "No message types in this range.",
    noPolls: "No polls in this range.",
    noHighlights: "Highlights appear after chats load.",
    noGenericData: "No data available.",
  },
  relayLog: {
    empty: "No logs yet.",
  },
};
