// @ts-check

/**
 * @param {{
 *   dom: Record<string, any>,
 *   state: Record<string, any>,
 *   wiring: Record<string, any>,
 *   withGlobalBusy: <T>(task: () => Promise<T> | T, message?: string) => Promise<T>,
 *   applyEntriesToApp: (...args: any[]) => Promise<any>,
 * }} params
 */
export function createRelayCompositionAdapter({ dom, state, wiring, withGlobalBusy, applyEntriesToApp }) {
  return {
    relayElements: {
      relayStartButton: dom.relayStartButton,
      relayStopButton: dom.relayStopButton,
      relayLogoutButton: dom.relayLogoutButton,
      relayReloadAllButton: dom.relayReloadAllButton,
      relayStatusEl: dom.relayStatusEl,
      relayAccountEl: dom.relayAccountEl,
      relayQrContainer: dom.relayQrContainer,
      relayQrImage: dom.relayQrImage,
      relayHelpText: dom.relayHelpText,
      relayBannerEl: dom.relayBannerEl,
      relayBannerMessage: dom.relayBannerMessage,
      relayBannerMeta: dom.relayBannerMeta,
      relayBannerActions: dom.relayBannerActions,
      relayRecoveryReconnectButton: dom.relayRecoveryReconnectButton,
      relayRecoveryResyncButton: dom.relayRecoveryResyncButton,
      relayRecoveryExportButton: dom.relayRecoveryExportButton,
      relayOnboardingSteps: dom.relayOnboardingSteps,
      logDrawerToggleButton: dom.logDrawerToggleButton,
      logDrawerEl: dom.logDrawerEl,
      logDrawerList: dom.logDrawerList,
      logDrawerConnectionLabel: dom.logDrawerConnectionLabel,
      relayClearStorageButton: dom.relayClearStorageButton,
      relaySyncProgressEl: dom.relaySyncProgressEl,
      relaySyncChatsMeta: dom.relaySyncChatsMeta,
      relaySyncMessagesMeta: dom.relaySyncMessagesMeta,
      firstRunSetup: dom.firstRunSetup,
      firstRunSetupSteps: dom.firstRunSetupSteps,
      firstRunOpenRelayButton: dom.firstRunOpenRelayButton,
      firstRunPrimaryActionButton: dom.firstRunPrimaryActionButton,
    },
    relayHelpers: {
      updateStatus: state.updateStatus,
      withGlobalBusy,
      fetchJson: state.fetchJson,
      setRemoteChatList: wiring.setRemoteChatList,
      getRemoteChatList: wiring.getRemoteChatList,
      getRemoteChatsLastFetchedAt: wiring.getRemoteChatsLastFetchedAt,
      refreshChatSelector: wiring.refreshChatSelector,
      setDashboardLoadingState: wiring.setDashboardLoadingState,
      setDatasetEmptyMessage: state.setDatasetEmptyMessage,
      setDataAvailabilityState: wiring.setDataAvailabilityState,
      getDataAvailable: wiring.getDataAvailable,
      getDatasetLabel: state.getDatasetLabel,
      updateHeroRelayStatus: wiring.updateHeroRelayStatus,
      applyEntriesToApp,
      encodeChatSelectorValue: wiring.encodeChatSelectorValue,
    },
    bootstrapElements: {
      relayStartButton: dom.relayStartButton,
      relayStatusEl: dom.relayStatusEl,
      relayStopButton: dom.relayStopButton,
      relayLogoutButton: dom.relayLogoutButton,
      relayReloadAllButton: dom.relayReloadAllButton,
      relayClearStorageButton: dom.relayClearStorageButton,
      logDrawerToggleButton: dom.logDrawerToggleButton,
      logDrawerCloseButton: dom.logDrawerCloseButton,
      logDrawerExportButton: dom.logDrawerExportButton,
      logDrawerReportButton: dom.logDrawerReportButton,
      logDrawerClearButton: dom.logDrawerClearButton,
      firstRunOpenRelayButton: dom.firstRunOpenRelayButton,
      firstRunPrimaryActionButton: dom.firstRunPrimaryActionButton,
      relayRecoveryReconnectButton: dom.relayRecoveryReconnectButton,
      relayRecoveryResyncButton: dom.relayRecoveryResyncButton,
      relayRecoveryExportButton: dom.relayRecoveryExportButton,
    },
  };
}
