export function createRuntimeEventBindings({
  filterRefs,
  exportRefs,
  dashboardRefs,
  handlers,
  deps,
}) {
  return {
    elements: {
      chatSelector: filterRefs.chatSelector,
      rangeSelect: filterRefs.rangeSelect,
      customApplyButton: filterRefs.customApplyButton,
      customStartInput: filterRefs.customStartInput,
      customEndInput: filterRefs.customEndInput,
      downloadParticipantsButton: exportRefs.downloadParticipantsButton,
      downloadHourlyButton: exportRefs.downloadHourlyButton,
      downloadDailyButton: exportRefs.downloadDailyButton,
      downloadWeeklyButton: exportRefs.downloadWeeklyButton,
      downloadWeekdayButton: exportRefs.downloadWeekdayButton,
      downloadTimeOfDayButton: exportRefs.downloadTimeOfDayButton,
      downloadMessageTypesButton: exportRefs.downloadMessageTypesButton,
      downloadChatJsonButton: exportRefs.downloadChatJsonButton,
      downloadSentimentButton: exportRefs.downloadSentimentButton,
      downloadMarkdownButton: exportRefs.downloadMarkdownButton,
      downloadSlidesButton: exportRefs.downloadSlidesButton,
      downloadSearchButton: exportRefs.downloadSearchButton,
      downloadPdfButton: exportRefs.downloadPdfButton,
      participantsTopSelect: dashboardRefs.participantsTopSelect,
      participantsSortSelect: dashboardRefs.participantsSortSelect,
      participantsTimeframeSelect: dashboardRefs.participantsTimeframeSelect,
      participantPresetButtons: dashboardRefs.participantPresetButtons,
      participantsBody: dashboardRefs.participantsBody,
      weekdayToggleWeekdays: filterRefs.weekdayToggleWeekdays,
      weekdayToggleWeekends: filterRefs.weekdayToggleWeekends,
      weekdayToggleWorking: filterRefs.weekdayToggleWorking,
      weekdayToggleOffhours: filterRefs.weekdayToggleOffhours,
      timeOfDayWeekdayToggle: filterRefs.timeOfDayWeekdayToggle,
      timeOfDayWeekendToggle: filterRefs.timeOfDayWeekendToggle,
      timeOfDayHourStartInput: filterRefs.timeOfDayHourStartInput,
      timeOfDayHourEndInput: filterRefs.timeOfDayHourEndInput,
      weekdayHourStartInput: filterRefs.weekdayHourStartInput,
      weekdayHourEndInput: filterRefs.weekdayHourEndInput,
    },
    handlers: {
      handleChatSelectionChange: handlers.handleChatSelectionChange,
      handleRangeChange: handlers.handleRangeChange,
      exportParticipants: handlers.exportParticipants,
      exportHourly: handlers.exportHourly,
      exportDaily: handlers.exportDaily,
      exportWeekly: handlers.exportWeekly,
      exportWeekday: handlers.exportWeekday,
      exportTimeOfDay: handlers.exportTimeOfDay,
      exportMessageTypes: handlers.exportMessageTypes,
      exportChatJson: handlers.exportChatJson,
      exportSentiment: handlers.exportSentiment,
      exportMessageSubtype: handlers.exportMessageSubtype,
      handleDownloadMarkdownReport: handlers.handleDownloadMarkdownReport,
      handleDownloadSlidesReport: handlers.handleDownloadSlidesReport,
      exportSearchResults: handlers.exportSearchResults,
      handleDownloadPdfReport: handlers.handleDownloadPdfReport,
      handleParticipantsTopChange: handlers.handleParticipantsTopChange,
      handleParticipantsSortChange: handlers.handleParticipantsSortChange,
      handleParticipantsTimeframeChange: handlers.handleParticipantsTimeframeChange,
      handleParticipantPresetClick: handlers.handleParticipantPresetClick,
      handleParticipantRowToggle: handlers.handleParticipantRowToggle,
    },
    deps: {
      updateStatus: deps.updateStatus,
      applyCustomRange: deps.applyCustomRange,
      updateWeekdayState: deps.updateWeekdayState,
      ensureWeekdayDayFilters: deps.ensureWeekdayDayFilters,
      rerenderWeekdayFromState: deps.rerenderWeekdayFromState,
      ensureWeekdayHourFilters: deps.ensureWeekdayHourFilters,
      updateHourlyState: deps.updateHourlyState,
      getHourlyState: deps.getHourlyState,
      ensureDayFilters: deps.ensureDayFilters,
      syncHourlyControlsWithState: deps.syncHourlyControlsWithState,
      rerenderHourlyFromState: deps.rerenderHourlyFromState,
    },
  };
}

export function createRuntimeBootstrapDeps({ deps, relayServiceName }) {
  return {
    initRelayControls: deps.initRelayControls,
    initThemeControls: deps.initThemeControls,
    setDataAvailabilityState: deps.setDataAvailabilityState,
    startRelaySession: deps.startRelaySession,
    stopRelaySession: deps.stopRelaySession,
    searchController: deps.searchController,
    savedViewsController: deps.savedViewsController,
    getDataAvailable: deps.getDataAvailable,
    refreshChatSelector: deps.refreshChatSelector,
    updateStatus: deps.updateStatus,
    relayServiceName,
  };
}
